apiVersion: v1
kind: Service
metadata:
  name: my-java-service
spec:
  selector:
    app: my-java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Optional: specify a port between 30000–32767
  type: NodePort
